version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: tl_classification_aws
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - .:/tl_classifier_web_app
    ports:
      - "8000:8000"